# Generated by Django 3.1.7 on 2021-03-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sonnets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonnet',
            name='highlighted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
